### ISSUE TITLE
Some question about the code 

### ISSUE THREAD

**Issue by ttxskk** [saeed1262/MoVi-Toolbox#1]
Hi ,I'm sorry to bother you,but can you tell me what's the meaning of [these](https://github.com/saeed1262/MoVi-Toolbox/blob/e419618abf036a54be79fa3d6bb8ac44c3275b61/MoCap/utils.py#L170-L173) code.
Thanks !

**Comment by saeed1262** [comment]
Hi,
The coordinate system in the AMASS data is a rotated version of our coordinate system. Therefore, to redo this we swap the x and y axes and change the sign of the x-axis

**Comment by ttxskk** [comment]
Thank you very much. This reply helped me solve the problem.
