### ISSUE TITLE
S_v3d_Subject_<ID>.mat and imu_Subject<ID>.bvh are missing

### ISSUE THREAD

**Issue by fandulu** [saeed1262/MoVi-Toolbox#11]
Hi @saeed1262 @ugnelis , thanks for your great work. May I ask a question? It seems that S_v3d_Subject_<ID>.mat and imu_Subject<ID>.bvh are missing from the download list, but they are important to be used to match with the imu data. Could you provide more information?

**Comment by saeed1262** [comment]
Hi,

All S_v3d MATLAB files are stored as S_V3D.tar.
As for the IMU bvh files, unfortunately we cannot share it at the moment but working on it.

**Comment by fandulu** [comment]
Got it. Thanks very much!
