### ISSUE TITLE
Matlab example doesn't work on Linux

### ISSUE THREAD

**Issue by ugnelis** [saeed1262/MoVi-Toolbox#4]
Hi,

I have Matlab 2017a, and I cannot run the tutorial. Matlab says that `.mlx` files are not supported on Linux.

Is it possible to get this example in Python?
![image](https://user-images.githubusercontent.com/8350893/90600348-5d036580-e231-11ea-81dd-c917b60efb65.png)

Best Regards,
Ugnius

**Comment by saeed1262** [comment]
Hi Ugnius,

I just added the m-file version as well.
I am also planning to add the Python version but you can use the code provided in https://github.com/vchoutas/smplify-x

Saeed

**Comment by ugnelis** [comment]
Thank you Saeed!
