### ISSUE TITLE
Question regarding F_Subject_1_L1.avi

### ISSUE THREAD

**Issue by ugnelis** [saeed1262/MoVi-Toolbox#5]
Hey Saeed,

Could you tell me from where I can download F_Subject_1_L1.avi file and similar ones. I can't find it in https://www.biomotionlab.ca/movi/

BR,
Ugnius

**Comment by saeed1262** [comment]
Hi Ugnius,

These video files are stored in dataverse:
https://dataverse.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5683/SP2/JRHDRN
with the name formats "F_PG1_Subject_**_L.avi" and "F_PG2_Subject_**_L.avi" for the first and second computer vision cameras, respectively. If you only want to download these files type "F_PG" in the search box and select all and download.

If you need more information on how to download, you can read the tutorial provided in the download section of https://www.biomotionlab.ca/movi/ or click on this link: https://www.biomotionlab.ca/Data/Tutorials/DataverseTutorialBMLmoviV2.pdf

**Comment by ugnelis** [comment]
Hi Saeed,

Thanks for the info. I have found those but I need videos splitted into motions as in the example (F_PG1_Subject_1_L**1**.avi). I hope you understand what I mean

**Comment by saeed1262** [comment]
You should trim F_PG1_Subject_[subject_num]_L.avi files into single motions using `single_videos.m` function.
Please check "Important Notes" on the main page and let me know if that solves your problem

**Comment by ugnelis** [comment]
Understood, thank you
