### ISSUE TITLE
Mean limb offset and FK script

### ISSUE THREAD

**Issue by alecda573** [saeed1262/MoVi-Toolbox#6]
Hi Saeed, 

Where can I find the mean limb offsets and did you guys decide to make public an FK script to convert the Exp maps to the join locations?

Thanks.

**Comment by saeed1262** [comment]
Hi,

If you are working on the AMASS representations, the FK is [here](https://github.com/saeed1262/MoVi-Toolbox/blob/352621e742ff8f745c3ada417d3db22d0ddf31ae/MoCap/utils.py#L130). If you are going to have the same skeletal size for all samples, you should set betas to all zeros (or your custom shape parameters) inside this function. Also make sure that you install all [AMASS dependencies](https://github.com/nghorbani/amass#installation).
For the V3D I haven't written any FK yet. Hopefully soon.

**Comment by alecda573** [comment]
@saeed1262 Thanks for this response. Can you answer a couple more questions possibly?

1) The amass_fk function is calling for a npz file path, but no npz file are in the database, what are these suppose to be exactly? 
2) If the npz files are not available, what is the key 'poses' referring to in the .mat files? Is this the ExpMaps?

**Comment by saeed1262** [comment]
> @saeed1262 Thanks for this response. Can you answer a couple more questions possibly?
> 
> 1. The amass_fk function is calling for a npz file path, but no npz file are in the database, what are these suppose to be exactly?
> 2. If the npz files are not available, what is the key 'poses' referring to in the .mat files? Is this the ExpMaps?

Hi,
The npz files are original AMASS versions of our dataset which should be downloaded separately [here](https://amass.is.tue.mpg.de/)
Please follow [this tutorial](https://github.com/saeed1262/MoVi-Toolbox/blob/master/MoCap/tutorial_python.ipynb)

The mean limb offsets are inherently in the body model. But shouldn't be hard to extract it.

**Comment by alecda573** [comment]
@saeed1262  

Maybe you could shed some light on this issue. If I use the amass_fk script on the .npz files I get the correct skeleton output when plotted. On the other hand, if I use the data taken from the .mat files (amass) I get skewed, distorted, and elongated skeletons.

**Comment by alecda573** [comment]
@saeed1262 One other question, at what hz is the data recorded in the npz format, 30 or 120?

**Comment by saeed1262** [comment]
It is 120. But the video data fps is 30.

**Comment by alecda573** [comment]
Thanks @saeed1262 any ideas about the other question?
