### ISSUE TITLE
About  SMPL coordinate to image coordinate!!!

### ISSUE THREAD

**Issue by Z-Z-J** [saeed1262/MoVi-Toolbox#8]
![QQ截图20210709105824](https://user-images.githubusercontent.com/53818279/125016929-c0de8900-e0a4-11eb-898a-21383c41370d.png)
![QQ截图20210709111630](https://user-images.githubusercontent.com/53818279/125018175-2764a680-e0a7-11eb-8baa-34cfed6c990c.png)
First, is there anything wrong with my idea?
Second,It doesn't look right, can you give me a sample code?
![QQ截图20210709112352](https://user-images.githubusercontent.com/53818279/125018694-326c0680-e0a8-11eb-8a38-f1e1ca4c5732.png)

**Comment by saeed1262** [comment]
Hi,
The first and second axes in video and AMASS data are different. Basically AMASS.x = video.y and AMASS.y = video.x.
Please check [this function](https://github.com/saeed1262/MoVi-Toolbox/blob/352621e742ff8f745c3ada417d3db22d0ddf31ae/MoCap/utils.py#L163) which converts AMASS data to coordinates compatible with video data
