### ISSUE TITLE
How to project marker data on CP1/2 videos?

### ISSUE THREAD

**Issue by isarandi** [saeed1262/MoVi-Toolbox#9]
First of all, thanks for this useful dataset! Can you please explain how to project marker/joint/keypoint data onto the CP1/CP2 videos? I can only find calibration data for PG1/PG2 videos, which have lower quality.

**Comment by saeed1262** [comment]
Hi,
Thanks for your interest.
Please follow [this tutorial](https://github.com/saeed1262/MoVi-Toolbox/blob/master/MoCap/tutorial_python.ipynb).

**Comment by isarandi** [comment]
Hi Saeed, maybe I'm looking at it wrong, but I can't find any reference to the CP1 and CP2 videos in this repository (including the tutorial you linked). I just want to make sure I understand correctly that only the PG1 and PG2 videos can be used for projecting the poses. Since CP2 is a handheld camera, I suspect that may not have calibration matrices. Just want to be sure.

**Comment by saeed1262** [comment]
Sorry. I thought we are talking about PG cameras. Yes, unfortunately, there is no calibration matrices for the CP cameras.
